/* tslint:disable */
/* eslint-disable */
/**
 * IMX Market Trader
 * IMX Market Trader backend API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Collection } from '../models';
import { CreateCollectionDto } from '../models';
import { DeleteResult } from '../models';
/**
 * CollectionsApi - axios parameter creator
 * @export
 */
export const CollectionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Count collections
         * @param {string} [collectionId] 
         * @param {string} [collectionAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        collectionsControllerCount: async (collectionId?: string, collectionAddress?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/collections/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (collectionId !== undefined) {
                localVarQueryParameter['collectionId'] = collectionId;
            }

            if (collectionAddress !== undefined) {
                localVarQueryParameter['collectionAddress'] = collectionAddress;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create collection
         * @param {CreateCollectionDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        collectionsControllerCreate: async (body: CreateCollectionDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling collectionsControllerCreate.');
            }
            const localVarPath = `/collections`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || (localVarRequestOptions.headers && localVarRequestOptions.headers['Content-Type'] === 'application/json');
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete collections
         * @param {string} collectionId 
         * @param {string} [collectionAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        collectionsControllerDelete: async (collectionId: string, collectionAddress?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'collectionId' is not null or undefined
            if (collectionId === null || collectionId === undefined) {
                throw new RequiredError('collectionId','Required parameter collectionId was null or undefined when calling collectionsControllerDelete.');
            }
            const localVarPath = `/collections`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (collectionId !== undefined) {
                localVarQueryParameter['collectionId'] = collectionId;
            }

            if (collectionAddress !== undefined) {
                localVarQueryParameter['collectionAddress'] = collectionAddress;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find collections
         * @param {string} [collectionId] 
         * @param {string} [collectionAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        collectionsControllerFind: async (collectionId?: string, collectionAddress?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/collections`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (collectionId !== undefined) {
                localVarQueryParameter['collectionId'] = collectionId;
            }

            if (collectionAddress !== undefined) {
                localVarQueryParameter['collectionAddress'] = collectionAddress;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CollectionsApi - functional programming interface
 * @export
 */
export const CollectionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Count collections
         * @param {string} [collectionId] 
         * @param {string} [collectionAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async collectionsControllerCount(collectionId?: string, collectionAddress?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<number>>> {
            const localVarAxiosArgs = await CollectionsApiAxiosParamCreator(configuration).collectionsControllerCount(collectionId, collectionAddress, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create collection
         * @param {CreateCollectionDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async collectionsControllerCreate(body: CreateCollectionDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Collection>>>> {
            const localVarAxiosArgs = await CollectionsApiAxiosParamCreator(configuration).collectionsControllerCreate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete collections
         * @param {string} collectionId 
         * @param {string} [collectionAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async collectionsControllerDelete(collectionId: string, collectionAddress?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DeleteResult>>> {
            const localVarAxiosArgs = await CollectionsApiAxiosParamCreator(configuration).collectionsControllerDelete(collectionId, collectionAddress, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Find collections
         * @param {string} [collectionId] 
         * @param {string} [collectionAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async collectionsControllerFind(collectionId?: string, collectionAddress?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Collection>>>> {
            const localVarAxiosArgs = await CollectionsApiAxiosParamCreator(configuration).collectionsControllerFind(collectionId, collectionAddress, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CollectionsApi - factory interface
 * @export
 */
export const CollectionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Count collections
         * @param {string} [collectionId] 
         * @param {string} [collectionAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async collectionsControllerCount(collectionId?: string, collectionAddress?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<number>> {
            return CollectionsApiFp(configuration).collectionsControllerCount(collectionId, collectionAddress, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create collection
         * @param {CreateCollectionDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async collectionsControllerCreate(body: CreateCollectionDto, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Collection>>> {
            return CollectionsApiFp(configuration).collectionsControllerCreate(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete collections
         * @param {string} collectionId 
         * @param {string} [collectionAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async collectionsControllerDelete(collectionId: string, collectionAddress?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<DeleteResult>> {
            return CollectionsApiFp(configuration).collectionsControllerDelete(collectionId, collectionAddress, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find collections
         * @param {string} [collectionId] 
         * @param {string} [collectionAddress] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async collectionsControllerFind(collectionId?: string, collectionAddress?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Collection>>> {
            return CollectionsApiFp(configuration).collectionsControllerFind(collectionId, collectionAddress, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CollectionsApi - object-oriented interface
 * @export
 * @class CollectionsApi
 * @extends {BaseAPI}
 */
export class CollectionsApi extends BaseAPI {
    /**
     * 
     * @summary Count collections
     * @param {string} [collectionId] 
     * @param {string} [collectionAddress] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionsApi
     */
    public async collectionsControllerCount(collectionId?: string, collectionAddress?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<number>> {
        return CollectionsApiFp(this.configuration).collectionsControllerCount(collectionId, collectionAddress, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create collection
     * @param {CreateCollectionDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionsApi
     */
    public async collectionsControllerCreate(body: CreateCollectionDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Collection>>> {
        return CollectionsApiFp(this.configuration).collectionsControllerCreate(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete collections
     * @param {string} collectionId 
     * @param {string} [collectionAddress] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionsApi
     */
    public async collectionsControllerDelete(collectionId: string, collectionAddress?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<DeleteResult>> {
        return CollectionsApiFp(this.configuration).collectionsControllerDelete(collectionId, collectionAddress, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Find collections
     * @param {string} [collectionId] 
     * @param {string} [collectionAddress] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionsApi
     */
    public async collectionsControllerFind(collectionId?: string, collectionAddress?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Collection>>> {
        return CollectionsApiFp(this.configuration).collectionsControllerFind(collectionId, collectionAddress, options).then((request) => request(this.axios, this.basePath));
    }
}
