/* tslint:disable */
/* eslint-disable */
/**
 * IMX Market Trader
 * IMX Market Trader backend API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CreateLimitOrderDto } from '../models';
import { DeleteResult } from '../models';
import { LimitOrder } from '../models';
/**
 * LimitOrdersApi - axios parameter creator
 * @export
 */
export const LimitOrdersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Count limit orders
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {string} [orderType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        limitOrdersControllerCount: async (walletId?: string, collectionId?: string, assetName?: string, orderType?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/limit-orders/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (walletId !== undefined) {
                localVarQueryParameter['walletId'] = walletId;
            }

            if (collectionId !== undefined) {
                localVarQueryParameter['collectionId'] = collectionId;
            }

            if (assetName !== undefined) {
                localVarQueryParameter['assetName'] = assetName;
            }

            if (orderType !== undefined) {
                localVarQueryParameter['orderType'] = orderType;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create limit order
         * @param {CreateLimitOrderDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        limitOrdersControllerCreate: async (body: CreateLimitOrderDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling limitOrdersControllerCreate.');
            }
            const localVarPath = `/limit-orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || (localVarRequestOptions.headers && localVarRequestOptions.headers['Content-Type'] === 'application/json');
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete limit orders
         * @param {string} walletId 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {string} [orderType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        limitOrdersControllerDeleteLimitOrders: async (walletId: string, collectionId?: string, assetName?: string, orderType?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'walletId' is not null or undefined
            if (walletId === null || walletId === undefined) {
                throw new RequiredError('walletId','Required parameter walletId was null or undefined when calling limitOrdersControllerDeleteLimitOrders.');
            }
            const localVarPath = `/limit-orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (walletId !== undefined) {
                localVarQueryParameter['walletId'] = walletId;
            }

            if (collectionId !== undefined) {
                localVarQueryParameter['collectionId'] = collectionId;
            }

            if (assetName !== undefined) {
                localVarQueryParameter['assetName'] = assetName;
            }

            if (orderType !== undefined) {
                localVarQueryParameter['orderType'] = orderType;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find limit orders
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {string} [orderType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        limitOrdersControllerFind: async (walletId?: string, collectionId?: string, assetName?: string, orderType?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/limit-orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (walletId !== undefined) {
                localVarQueryParameter['walletId'] = walletId;
            }

            if (collectionId !== undefined) {
                localVarQueryParameter['collectionId'] = collectionId;
            }

            if (assetName !== undefined) {
                localVarQueryParameter['assetName'] = assetName;
            }

            if (orderType !== undefined) {
                localVarQueryParameter['orderType'] = orderType;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LimitOrdersApi - functional programming interface
 * @export
 */
export const LimitOrdersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Count limit orders
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {string} [orderType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async limitOrdersControllerCount(walletId?: string, collectionId?: string, assetName?: string, orderType?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<number>>> {
            const localVarAxiosArgs = await LimitOrdersApiAxiosParamCreator(configuration).limitOrdersControllerCount(walletId, collectionId, assetName, orderType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create limit order
         * @param {CreateLimitOrderDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async limitOrdersControllerCreate(body: CreateLimitOrderDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LimitOrder>>> {
            const localVarAxiosArgs = await LimitOrdersApiAxiosParamCreator(configuration).limitOrdersControllerCreate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete limit orders
         * @param {string} walletId 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {string} [orderType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async limitOrdersControllerDeleteLimitOrders(walletId: string, collectionId?: string, assetName?: string, orderType?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DeleteResult>>> {
            const localVarAxiosArgs = await LimitOrdersApiAxiosParamCreator(configuration).limitOrdersControllerDeleteLimitOrders(walletId, collectionId, assetName, orderType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Find limit orders
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {string} [orderType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async limitOrdersControllerFind(walletId?: string, collectionId?: string, assetName?: string, orderType?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<LimitOrder>>>> {
            const localVarAxiosArgs = await LimitOrdersApiAxiosParamCreator(configuration).limitOrdersControllerFind(walletId, collectionId, assetName, orderType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * LimitOrdersApi - factory interface
 * @export
 */
export const LimitOrdersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Count limit orders
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {string} [orderType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async limitOrdersControllerCount(walletId?: string, collectionId?: string, assetName?: string, orderType?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<number>> {
            return LimitOrdersApiFp(configuration).limitOrdersControllerCount(walletId, collectionId, assetName, orderType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create limit order
         * @param {CreateLimitOrderDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async limitOrdersControllerCreate(body: CreateLimitOrderDto, options?: AxiosRequestConfig): Promise<AxiosResponse<LimitOrder>> {
            return LimitOrdersApiFp(configuration).limitOrdersControllerCreate(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete limit orders
         * @param {string} walletId 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {string} [orderType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async limitOrdersControllerDeleteLimitOrders(walletId: string, collectionId?: string, assetName?: string, orderType?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<DeleteResult>> {
            return LimitOrdersApiFp(configuration).limitOrdersControllerDeleteLimitOrders(walletId, collectionId, assetName, orderType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find limit orders
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {string} [orderType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async limitOrdersControllerFind(walletId?: string, collectionId?: string, assetName?: string, orderType?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<LimitOrder>>> {
            return LimitOrdersApiFp(configuration).limitOrdersControllerFind(walletId, collectionId, assetName, orderType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LimitOrdersApi - object-oriented interface
 * @export
 * @class LimitOrdersApi
 * @extends {BaseAPI}
 */
export class LimitOrdersApi extends BaseAPI {
    /**
     * 
     * @summary Count limit orders
     * @param {string} [walletId] 
     * @param {string} [collectionId] 
     * @param {string} [assetName] 
     * @param {string} [orderType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LimitOrdersApi
     */
    public async limitOrdersControllerCount(walletId?: string, collectionId?: string, assetName?: string, orderType?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<number>> {
        return LimitOrdersApiFp(this.configuration).limitOrdersControllerCount(walletId, collectionId, assetName, orderType, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create limit order
     * @param {CreateLimitOrderDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LimitOrdersApi
     */
    public async limitOrdersControllerCreate(body: CreateLimitOrderDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<LimitOrder>> {
        return LimitOrdersApiFp(this.configuration).limitOrdersControllerCreate(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete limit orders
     * @param {string} walletId 
     * @param {string} [collectionId] 
     * @param {string} [assetName] 
     * @param {string} [orderType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LimitOrdersApi
     */
    public async limitOrdersControllerDeleteLimitOrders(walletId: string, collectionId?: string, assetName?: string, orderType?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<DeleteResult>> {
        return LimitOrdersApiFp(this.configuration).limitOrdersControllerDeleteLimitOrders(walletId, collectionId, assetName, orderType, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Find limit orders
     * @param {string} [walletId] 
     * @param {string} [collectionId] 
     * @param {string} [assetName] 
     * @param {string} [orderType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LimitOrdersApi
     */
    public async limitOrdersControllerFind(walletId?: string, collectionId?: string, assetName?: string, orderType?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<LimitOrder>>> {
        return LimitOrdersApiFp(this.configuration).limitOrdersControllerFind(walletId, collectionId, assetName, orderType, options).then((request) => request(this.axios, this.basePath));
    }
}
