/* tslint:disable */
/* eslint-disable */
/**
 * IMX Market Trader
 * IMX Market Trader backend API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { NftAssets } from '../models';
/**
 * NftAssetsApi - axios parameter creator
 * @export
 */
export const NftAssetsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Count nft assets
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nftAssetsControllerCount: async (walletId?: string, collectionId?: string, assetName?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/nft-assets/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (walletId !== undefined) {
                localVarQueryParameter['walletId'] = walletId;
            }

            if (collectionId !== undefined) {
                localVarQueryParameter['collectionId'] = collectionId;
            }

            if (assetName !== undefined) {
                localVarQueryParameter['assetName'] = assetName;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find nft assets
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nftAssetsControllerFindNftAssets: async (walletId?: string, collectionId?: string, assetName?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/nft-assets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (walletId !== undefined) {
                localVarQueryParameter['walletId'] = walletId;
            }

            if (collectionId !== undefined) {
                localVarQueryParameter['collectionId'] = collectionId;
            }

            if (assetName !== undefined) {
                localVarQueryParameter['assetName'] = assetName;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NftAssetsApi - functional programming interface
 * @export
 */
export const NftAssetsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Count nft assets
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nftAssetsControllerCount(walletId?: string, collectionId?: string, assetName?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<number>>> {
            const localVarAxiosArgs = await NftAssetsApiAxiosParamCreator(configuration).nftAssetsControllerCount(walletId, collectionId, assetName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Find nft assets
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nftAssetsControllerFindNftAssets(walletId?: string, collectionId?: string, assetName?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<NftAssets>>>> {
            const localVarAxiosArgs = await NftAssetsApiAxiosParamCreator(configuration).nftAssetsControllerFindNftAssets(walletId, collectionId, assetName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * NftAssetsApi - factory interface
 * @export
 */
export const NftAssetsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Count nft assets
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nftAssetsControllerCount(walletId?: string, collectionId?: string, assetName?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<number>> {
            return NftAssetsApiFp(configuration).nftAssetsControllerCount(walletId, collectionId, assetName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find nft assets
         * @param {string} [walletId] 
         * @param {string} [collectionId] 
         * @param {string} [assetName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nftAssetsControllerFindNftAssets(walletId?: string, collectionId?: string, assetName?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<NftAssets>>> {
            return NftAssetsApiFp(configuration).nftAssetsControllerFindNftAssets(walletId, collectionId, assetName, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NftAssetsApi - object-oriented interface
 * @export
 * @class NftAssetsApi
 * @extends {BaseAPI}
 */
export class NftAssetsApi extends BaseAPI {
    /**
     * 
     * @summary Count nft assets
     * @param {string} [walletId] 
     * @param {string} [collectionId] 
     * @param {string} [assetName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NftAssetsApi
     */
    public async nftAssetsControllerCount(walletId?: string, collectionId?: string, assetName?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<number>> {
        return NftAssetsApiFp(this.configuration).nftAssetsControllerCount(walletId, collectionId, assetName, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Find nft assets
     * @param {string} [walletId] 
     * @param {string} [collectionId] 
     * @param {string} [assetName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NftAssetsApi
     */
    public async nftAssetsControllerFindNftAssets(walletId?: string, collectionId?: string, assetName?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<NftAssets>>> {
        return NftAssetsApiFp(this.configuration).nftAssetsControllerFindNftAssets(walletId, collectionId, assetName, options).then((request) => request(this.axios, this.basePath));
    }
}
