/* tslint:disable */
/* eslint-disable */
/**
 * IMX Market Trader
 * IMX Market Trader backend API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CreateNewWalletDto } from '../models';
import { CreateWalletDto } from '../models';
import { DeleteResult } from '../models';
import { Wallet } from '../models';
/**
 * WalletsApi - axios parameter creator
 * @export
 */
export const WalletsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Count wallets
         * @param {string} [walletId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        walletsControllerCount: async (walletId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wallets/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (walletId !== undefined) {
                localVarQueryParameter['walletId'] = walletId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create Wallet
         * @param {CreateWalletDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        walletsControllerCreate: async (body: CreateWalletDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling walletsControllerCreate.');
            }
            const localVarPath = `/wallets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || (localVarRequestOptions.headers && localVarRequestOptions.headers['Content-Type'] === 'application/json');
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create new wallet and register
         * @param {CreateNewWalletDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        walletsControllerCreateAndRegisterWallet: async (body: CreateNewWalletDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling walletsControllerCreateAndRegisterWallet.');
            }
            const localVarPath = `/wallets/create-and-register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || (localVarRequestOptions.headers && localVarRequestOptions.headers['Content-Type'] === 'application/json');
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete wallets
         * @param {string} walletId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        walletsControllerDelete: async (walletId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'walletId' is not null or undefined
            if (walletId === null || walletId === undefined) {
                throw new RequiredError('walletId','Required parameter walletId was null or undefined when calling walletsControllerDelete.');
            }
            const localVarPath = `/wallets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (walletId !== undefined) {
                localVarQueryParameter['walletId'] = walletId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find wallets
         * @param {string} [walletId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        walletsControllerFind: async (walletId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wallets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (walletId !== undefined) {
                localVarQueryParameter['walletId'] = walletId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WalletsApi - functional programming interface
 * @export
 */
export const WalletsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Count wallets
         * @param {string} [walletId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async walletsControllerCount(walletId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<number>>> {
            const localVarAxiosArgs = await WalletsApiAxiosParamCreator(configuration).walletsControllerCount(walletId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create Wallet
         * @param {CreateWalletDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async walletsControllerCreate(body: CreateWalletDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Wallet>>>> {
            const localVarAxiosArgs = await WalletsApiAxiosParamCreator(configuration).walletsControllerCreate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create new wallet and register
         * @param {CreateNewWalletDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async walletsControllerCreateAndRegisterWallet(body: CreateNewWalletDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Wallet>>>> {
            const localVarAxiosArgs = await WalletsApiAxiosParamCreator(configuration).walletsControllerCreateAndRegisterWallet(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete wallets
         * @param {string} walletId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async walletsControllerDelete(walletId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DeleteResult>>> {
            const localVarAxiosArgs = await WalletsApiAxiosParamCreator(configuration).walletsControllerDelete(walletId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Find wallets
         * @param {string} [walletId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async walletsControllerFind(walletId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Wallet>>>> {
            const localVarAxiosArgs = await WalletsApiAxiosParamCreator(configuration).walletsControllerFind(walletId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WalletsApi - factory interface
 * @export
 */
export const WalletsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Count wallets
         * @param {string} [walletId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async walletsControllerCount(walletId?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<number>> {
            return WalletsApiFp(configuration).walletsControllerCount(walletId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create Wallet
         * @param {CreateWalletDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async walletsControllerCreate(body: CreateWalletDto, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Wallet>>> {
            return WalletsApiFp(configuration).walletsControllerCreate(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create new wallet and register
         * @param {CreateNewWalletDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async walletsControllerCreateAndRegisterWallet(body: CreateNewWalletDto, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Wallet>>> {
            return WalletsApiFp(configuration).walletsControllerCreateAndRegisterWallet(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete wallets
         * @param {string} walletId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async walletsControllerDelete(walletId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<DeleteResult>> {
            return WalletsApiFp(configuration).walletsControllerDelete(walletId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find wallets
         * @param {string} [walletId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async walletsControllerFind(walletId?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Wallet>>> {
            return WalletsApiFp(configuration).walletsControllerFind(walletId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WalletsApi - object-oriented interface
 * @export
 * @class WalletsApi
 * @extends {BaseAPI}
 */
export class WalletsApi extends BaseAPI {
    /**
     * 
     * @summary Count wallets
     * @param {string} [walletId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApi
     */
    public async walletsControllerCount(walletId?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<number>> {
        return WalletsApiFp(this.configuration).walletsControllerCount(walletId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create Wallet
     * @param {CreateWalletDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApi
     */
    public async walletsControllerCreate(body: CreateWalletDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Wallet>>> {
        return WalletsApiFp(this.configuration).walletsControllerCreate(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create new wallet and register
     * @param {CreateNewWalletDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApi
     */
    public async walletsControllerCreateAndRegisterWallet(body: CreateNewWalletDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Wallet>>> {
        return WalletsApiFp(this.configuration).walletsControllerCreateAndRegisterWallet(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete wallets
     * @param {string} walletId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApi
     */
    public async walletsControllerDelete(walletId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<DeleteResult>> {
        return WalletsApiFp(this.configuration).walletsControllerDelete(walletId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Find wallets
     * @param {string} [walletId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletsApi
     */
    public async walletsControllerFind(walletId?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Wallet>>> {
        return WalletsApiFp(this.configuration).walletsControllerFind(walletId, options).then((request) => request(this.axios, this.basePath));
    }
}
