/* tslint:disable */
/* eslint-disable */
/**
 * IMX Market Trader
 * IMX Market Trader backend API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Mnemonic } from './mnemonic';
/**
 * 
 * @export
 * @interface CreateWalletDto
 */
export interface CreateWalletDto {
    /**
     * 
     * @type {string}
     * @memberof CreateWalletDto
     */
    _id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWalletDto
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWalletDto
     */
    l2Address: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWalletDto
     */
    publicKey: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWalletDto
     */
    privateKey: string;
    /**
     * 
     * @type {Mnemonic}
     * @memberof CreateWalletDto
     */
    mnemonic: Mnemonic;
    /**
     * 
     * @type {string}
     * @memberof CreateWalletDto
     */
    balance: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWalletDto
     */
    registered: string;
}
