/* tslint:disable */
/* eslint-disable */
/**
 * IMX Market Trader
 * IMX Market Trader backend API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NftAssets
 */
export interface NftAssets {
    /**
     * 
     * @type {string}
     * @memberof NftAssets
     */
    _id: string;
    /**
     * 
     * @type {string}
     * @memberof NftAssets
     */
    walletId: string;
    /**
     * 
     * @type {string}
     * @memberof NftAssets
     */
    collectionId: string;
    /**
     * 
     * @type {string}
     * @memberof NftAssets
     */
    collectionAddress: string;
    /**
     * 
     * @type {string}
     * @memberof NftAssets
     */
    assetName: string;
    /**
     * 
     * @type {number}
     * @memberof NftAssets
     */
    assetQuantity: number;
    /**
     * 
     * @type {Array<any>}
     * @memberof NftAssets
     */
    assets: Array<any>;
    /**
     * 
     * @type {Date}
     * @memberof NftAssets
     */
    lastModifiedDate?: Date;
}
